apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCNvsSGFINxnWGP7hH8rrd8lxmKMXHt0DXH2ZiI/hKpxTSeHW6i1VgMpUJkrPONzU77c8V7r5nvaWSaCU2jN7fqa+OtNs5QUa30pOT/igq39tvlxzuZ5PrmF06JNCnpPiPHjR1gn+STPn55QffC8vT/OC7nbbvFeIPghRVEHVkpdD6jt+A2oWKuLgHC14piUBIuaJncLXk34Coc6NPtU6utRjjmw1/a8dHC1eZ9gufnxCoLWvywXvXAAB9mZOjpI79X2vq5vzdxC1OBv8CvL6ZkpSElmwYXk0Y1rlzrSbIx+5vmyA0CbNcKSSF6hFiUC56X7y+Kw/GL5rIyHIWKs3Hty3QUXvXzgJROKQrNRqht9FeGBzvxqVLDyaFrXG95Qv6/sAVdRbnqcErErNHGBcWcgayNp8kQxG9hXGNweE1G1+T0vw9gNc7zIJOyOwEWTIl/qGhT356G5b8tmrJqQykRd/qDTitui2uvWnc7UOBJBhGZQn3k+kuEzbBJPoypispy5wzGoz53GwxlraMJdyoqXRFUsxWTVXY4H6Jk6Ipkj2GbPCwpC14hbBr7v9XtfyEiAhN3xWgfimaDc8ItCvtCOHjcVkdiaCQXkRduWe8D4HO4osYquLhhP0nJ9LX826jza96G5fMao1FMRX8tYYGSEwS4QlQ/+HRFrTvu9wnYbnACP2uuUC0fUBq3WcmE0lDw+6GyrvhXjVqYTG92GfWg9Ow1CfJvJoLPZYba+WzDXw9jar2ulw5lJCnpZXDQJ7CY9S1Bhz7Pui6caZ7PjzWzn9JWbYOBix+t6fjy8wxwqJZ7daNxlm54dfLiHydEQMZNaNfdLWFCngeO+AMiTzemf6mauPbofrWhzagescsy2ZHDQc9uFfvk/qQTkv5MPHi/Q/0C1OQeH3CAhBnf2mor2Qg2mIo=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

