apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAVo5G4auy60MmID90rzj+K0rD4j4IY+f8j8bJNzjjNT7J9i6fc5sI06D2u14XYk1YLJHAvdM1WR69W0F9+W7qj6kZmvbBaqRC3a3EgJ6qd+JS8l6U/lgnXTwSzue8o9sJd2uw3pi2+vPD0SCoiNm29kRZ8HIjKdwiv+8GkWc20Zh2OOy4fuDKst+8wuH58kplXyCwsDunADwbMJc0MJy/mywzrAGvhDljF3CdxlBGYOrYyKYYRd3R1j7E5HzvdabeNQYbsFWsEPKeP6XPoUbaUJICttDGzMGS4pv84O7f32d93+CfmcNxgNkBufOoX6kCChxAoPCS6j9NGWbbTg7gO+MNUcbj0FSQKwoGvgSktilH8sgLq5hGGcIHM0sDNFIwPguUF7QVUJ5SGXa33TfhDfxSiB/2Jq3uFraEu6bkxXKRHy4tx+wkCwOx7nQgrK18M42T6x7m2lElTlIMNEm7t9ZRNW+ipkHxmbmRwBLmPY5Mkp29PqpnihuYX5QZ6PJt3+X2OclBwRjcJtWaBC0RtT4KMgoigFAtEL1SrZAhfu7VKFxw7MH7Eo7opMHD0teh6nkPqnN1uVgCbfjdZLeq+7eULPRo5bGLYuDraetKxIo1QGTtsyzdh1ZdmXZE3zFuCUNpbVLFfvvuX4IRHjAnPvTpIJaVtsU7KMldbim9ey1OlJoVX9M7xqSzllySzlZBo2AVEGmqPRntkQdZRs0gPLSVgDAzRyQYrtduqpvVk/xl9S70mXGXEubogOj5Lh25oIGsUkB5b6z4rZ6O9iIbqRoHdcQSOyN93lG4nqzh7mYiZ5P1ikShtCelqVwJAnuPRp0hZjzsB136+pxHiyJSL9ViXgT9GmmHaVXzHYOMEuQv9qBUVBvkoHmYvrSOCj0VWbqvqPuUtIwrlL33SZvM44a/69v8=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

