apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argo
spec:
  encryptedData:
    .dockerconfigjson: AgB9m5XQA/P/1HxgS75dDFK+6VdWPkfncKB3ctGHEpyUjTBa1Tn+cgY1sbv2DaQMF5z8oO9AwJ/MlgOQLXPGaF9NoTnipAYxV0gD2CfbsuzttVU4eA4stM/qHFJc3c5Rfjc/24cayvAm12auVfPPmr+MO2S8MHusrF+BsOhRHrXHhnG91+mDiHQHCzvUSr++HVJpbVByX/wP+7yvlZzFWxEqWRwtKGRHOnsRS/sWF5JUHqWu0ZhEDdBWp8EppJz6rAzmbIZRt3lB8ZAtGbzdMiSjS1XjP433dm19SmH1j8pgGcWP+vuWGV76R87+3JqEY89VgZf/tPEXma+hnR1f20zShPJp76Hh5mydqopXBcskBQomQJmpw0vCMPRyrcT9zPTD30bxVBZ6npu1p+WBU1Ebm/g49rhE58hDYruWy+zOOxk3I9L12WqkbZjiQKmu/I0OBledRZUvQ6i+7/3e8dsRXBR7DNa4lvuTyU4BZef8s97hom2oxBNtxIdHU4wY2lXi7opiEHtvIyOph/e7mf/EvysNjaA/IyIcVLHC3/X1roxPV/t3/33+v07XbPn4D90p9AgzjSrDSBwGim+Ql7/1XbiPfFfGjjCkrnuZpHWvuWvlCs7j75X2KayKQLsfu7mwr4cEB2aax4Zq7A4mu5x+vkAoUrnY7QkKW5oAVc7EVFPCz7NVCmaZEy0CrKN1Kn0r5gc3UNH0JK2Hmj6yO00u4kYJUlcfoxPfbhQpV6iSzUpOW8/mJmrAJRWv2po93Q1efz2lQIBKgFU5GIg+Nq+hEYJmxhxb4ZvjFqxjZs0BA8Nk41XmJ3HrqFkO3fcSld/7QLoCvkCR6v6ygcT0bYTxrkrYetfSDOq5ehHufYwUPqllfyQ4nKGYvaY+DMKJijN3VQF3ap7g55FCwYv2pxBrdqDNWTwjv6axAk0olnAHZIhIOtIruZssBaJrPzThJM2Qb85OVNyOiCIXzQ9berTx4jiOD0ll
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argo
    type: kubernetes.io/dockerconfigjson

