apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argo
spec:
  encryptedData:
    .dockerconfigjson: AgBP7T8inlgJGvaPBrwHrouwRzQ0SbE/4HRpSaPb6cUVVm8b8Mm5HJrw8skSfEfeZK8mG59EjETUdKPwkMXAR0mGreQtjmSzlhOlYWAEeFiP/Cmqj15UFRlWbg2YE1NFWhfSeEgwoiJcojLxwC6xVvJmcz/ONJWE4PKM8ZpLABUiSmaxj+ZDr34xd0zVUlR5XrBm4lAY/Hhe0MiPnMKxsIITZSiFpo1ncyOvT6vmTtprtCWvyP15ixYHkbKc4BlGjt4aqxMomzybB4fo7IdjzubP9w8voewa/lK6QsLC/AoEODTE0F2KI827VDFfE0Rz+zFnxDJRHYy3F1+2ZK0SJcCk3MGvUoYrNhVmimGOPRxECunB7ZYcooeWNOygK4dzpO+QjdqxTh7Y4qpl15Y3CqCwoaMf4DtvmAI1o6gD6M13Rdb5/BDyEqoJLKGpLTOdc+sJrGD4U3nTLKmgw5LyJHuM2sHWl3HiXPT8D5Oa9pYxv9zaBotiZo9LBBaL+4EwNhWoPKjxPzSolvzZxk8WsIKur4IE7Pyi2iLYZIJG3tZdmIy6EP63+b49LCPJmOaWOsUTlcXyXI8l2+LOP5juhEzr313Nyj19njXHert3Cr67LpICGrnXlGoix4xjK6BbLHAsuJ//QgBX1JdW7oXvSEQASdCVh9Ob8tuPkvGwqYELw3qtglnHc1iWPma2SzBQNkYaAPLdcHaBcfYVZjHyk1pgszn7PtnewgmH6Yupif3huRics2xXCFlDv05aqP2Et14ppZQvtzIzvA8CmB8AskvRvqieE98vV1bxm3k5lLZ8XAz7OOG5aL1rjQKPWFN6mKdSCXWimPRPzuD2GlPxFjCJ3CAAPCOVkpTLuxlMzTA/2u7Qc7dCITrGTSitabjPL/yDB9FC7cBRmsLLcYamJP11iFrgGoxRT0+9h0EvLfb9UrcNRYlSprG/CU3Px6a/pEzTELPTbocfH7YmMiWI720WRxJPy42e
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argo
    type: kubernetes.io/dockerconfigjson

