apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argo
spec:
  encryptedData:
    .dockerconfigjson: AgCwX89260j7HUXH3h9ej6FLM1IYm5q2114VaR6nuf6RgpmlPZe+t038pYeNYjK1PyU8TJ/HNmVTFFcBYD0R3+loYkSwSDQ/WFX8wMcDy6d+VUt2bFqrb77zi+Hw6W48Sel0uCtAwz5SnhAvfFPtmfiBaKH/qgHyQtWBYl2r0kvf4TUY+R8LrO8zEKNkS9WgG9mFwrMW9/oqbrDkh+zI7iH8sphy4pP35dhAbwPwyxnHCHHuwRmXe/zPBlmtTLVgZx9tQ9FHGtwbKVp5CejzLJ8Udr0klUEJzS8gs+c7eVbF6UHB/HWSZeA+xeGbiH3OMdfrV96IOKk1zADHMVsKNO8LQM6cSktd72R86z8pgZk85mt4IZrhHSyCSW3gxEd+5618xCcm/xZldoQzbJ/5VV/4Kdz6wA1OPJUKEu5UZLHsn5DF78xK821v1K9IuciDDDnpl88LMWrMTPhH+cnx0eXey4zoC3Bzz3gpheN8BW+WuHV+hkM3rx0hZ104t0X84bQSjRhwYX5OWQZ5Fu62cV+fyb2bV4csfbvQlYzDzhwgz8P9O3WBgiZyzrrMtjkGGuz9AIc1nyGmr7oK5iAHWcCBRo8pV+0apjkXxTy/ZebTujb8h8yP4XdphohI8SRJ5BZhxKSHOKU6AABip9+2I/dHy6ZSr0pAKOfeK4UyD606zApjP50rdyjZy68+jqNYO0303hNKHoeSJdnhjibIfFWmA4xpDDEzsl0gDQlUloVNyhSgdg0nPSzjfpivTeLY5qjIVy6QRSBT76TRJLn9YHS4UkD0HSnOD18giPvxBwyiiJrinS+q/pveedMulVNEhth0/szXKpAfUHKEWW28dn8avvSLBnVc5fVjwgFSzFEfL4kQGxOkRGlSoSxKO195C8QF8OJMuVs4T9Zj5TyuUXPS9pnvOYw9WBwJ8TizLf6kb/MInpJAkKaJcCU0nYDTpnn0RcdyFlVpv1T91h/cE0CTE+MRJdgU
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argo
    type: kubernetes.io/dockerconfigjson

