apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo

resources:
- namespace.yaml
- github.com/argoproj/argo/manifests/base?ref=stable
- github.com/argoproj/argo/manifests/cluster-install/workflow-controller-rbac?ref=stable
- github.com/argoproj/argo/manifests/cluster-install/argo-server-rbac?ref=stable
- templates.yaml
patchesStrategicMerge:
- config.yaml

patchesJson6902:
- path: patch/argo-cli/deployment-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: argo-server
    version: v1
- path: patch/argo-cli/service-patch.yaml
  target:
    kind: Service
    name: argo-server
    version: v1