apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- github.com/argoproj/argo/manifests/base?ref=stable
- github.com/argoproj/argo/manifests/cluster-install/workflow-controller-rbac?ref=stable
- github.com/argoproj/argo/manifests/cluster-install/argo-server-rbac?ref=stable
- templates.yaml
patchesStrategicMerge:
- config.yaml
namespace: argo
