apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

# replicas:
# - count: 2
#   name: argocd-redis-ha-server
# - count: 2
#   name: argocd-redis-ha-haproxy  
# - count: 2
#   name: argocd-repo-server
# - count: 2
#   name: argocd-server

resources:
- ../../base
- ingress.yaml
- route.yaml
- regcred.yaml

configMapGenerator:
- behavior: merge
  files:
  - env/resource.customizations
  - env/resource.exclusions
  name: argocd-cm
- behavior: merge
  files:
  - env/policy.csv
  - env/policy.default
  name: argocd-rbac-cm

patchesStrategicMerge:
- server.yaml

patchesJson6902:
- path: patch/redis/sc-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-redis
    version: v1
