apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- ../../base
- ingress.yaml

patchesStrategicMerge:
- server.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: argocd-redis
  path: patch/redis/sc-patch.yaml