apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgAKrhTpf/7ah64eRRptXX4F5yNPhBobYkiQ6mqKS15XZGNmyIjGw5Iu4TdRd7vIX+gDAWnGbum/gpXhr4ym9SOyYzimcJTCXPHJFOda6Mwh2fZ2I3131k8Sq3lnDGrEhK7yEnWDq0UWBo0JUPcZ7WSqogjjC2QNed1H3K2BfqNq1hZPStQh4VTB/AgLcrLF3ONbHncIpr/nk7IJ5+4moHCxA4XErUATPE+RrtFTNgEu/yt6B33dr9vCMN2cbdmUYUxSWvopzZgHM2qSVGWWYPrKKvoVT7cWuaXLTIw4wwBAEMp/jRbKjkPghvseRWLBEdndavWsJE4TVpOO8rButp/uNJZN+eWkxpzKWqBgRmMdl+DR8+FZBXfJ4N+HhOtNBdYdxImSJfZG/Jx6WYC1Ik/J7Ff1AQCLTssPUbtEerZuO4Ap2C1daEhfywbWfkft0ZeTPiKwwF1aon0R1YG6hobM7wui6HJAfNWEne9nyHQyGIthCdUNBlc4yJixgaEcaNA1lyLhxI2TFnEt4CmvF0h2DA/XKGLvIDmLHfmU47gww8bYoqzNm0yWMh3CauuGHbZk3LdWtd310bmVfTyOHSGOaiKXsaAbdgrR9r2eM0VzJKYIW+qByBdlnpLakzhAWFS+gMXfRFc39yEBWpNMKf8WUBKt/Z141N+i/bMlcfhvMWrMsfy7jQec0Oz/xs9SsclUGu54EYhpN5Uh5+0v+iButc5vQKrfPs3mKlTBb7t1m8kx2CbnsN/1awDn4z/PVEIvVYShuphwE9gnoqYmxejCKNB9Y90oLf4vL68lAaSpYKMNsNbgiuA89fjZmwV4KqFXifBu1MB0nw7GqrzC/Z3y/DmH5HVDzPBz9x+bF8KxL0cQTUCin8QIL5nPs8Nmqf1S+4VsYT521xiimniM4vCItd9fZ8PaUmQ1c2NseNb5nhV47lWaeEacflugTGUkPevrGhkxswyDWOhJBeaCYZ7as/9V/ZSo
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argocd
    type: kubernetes.io/dockerconfigjson

