apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgBXjtI0Z3qb0hqCXbgKPBxzy5kv5gXRiIMhvNot1zmvTw2TFTkYBMr2kdEexOw+JTRHssIDXa06zi7PE/YZyLHgipcAHqcMNOrD0j8bic9BF0K2YRkU3jG3eqoK5bBMcpMX0+QFCyiIqYjO5Jcx3jywFdtfNmgoRDNb1GjjqM0RVhmtFyM04zeBIwEbp1OKjjm0x7fEAs4BxE2RtmjGiKlOzKOeOPkoZho5v1zKcRLQKmAtydq+3uLcoZ5uvE2S+sQukssdfZvaKi/ODS+HKVXIr2wiC4uWrKsfCiryRAAHD50D1iPNAqsyPQSXtB8wkBYM5aQkVX6XafElrhhhljypiYBopZUyEt3yacfIQWJbLnXCnwgBjaRiMAtTMuH+8Dlr05P5v72xx4LMz/wE7ehiV9oETlNzSlgJWxsiq+MM1wXBtGo+Gzrlb5MI3TRtrsQ6IN6mBe4l8G1bZ0QY9qhZFqzibVRuG/B21mxHVKtL7U+Ve6IlDJ7onjNvmPCKMhtZi95fZHtiIBg9thav9OL3GT7uR9pAxkFZrMmYWj/JcdQoHEU69p0jD2gSXnnhBYXBUl18NSSU3Wcx5BRlLRnwaZHoGQMo8+XY6zBEgsaaSpUEr6N08zF8CJ3+NvqKDV/gyhzHL/xfJiQfgnFCokojdgXcEzaX4UMaYzz6L3I+0h4+Tb5SnyMR4jsbwjHpaDY57jq5mFoP0t4avHh77S9HRyDaltqE9iWrft9qZ0M6Debpuu6pfpwaA5b6+6NkkDXiZqasc1EH01pBSnJm0A3YDgDrezP+L676Sf62x8TzhIbkmCcdv+gSTMjUaVFldm4b9007OBKexyb8NbUVPgidZhttDQN25778J+beXicxm7J4Q724tKc7q//hKh0sejYl66TahJCiw1jxI+J1gHLrvS86w7uTkpk7K8EsViHy4gOSPRAtjO/4IIvkPYcLryaHbsXsFqVfyYAtwc5C9kdPUlCoo5n3
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argocd
    type: kubernetes.io/dockerconfigjson

