apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgAJ68yDvUNHOgPcbTnttsG3o7NXQpkkBZWt9sKBxZHCc41uuoF2CS2RamMyOTbuvjiBVGD1HAocZy4gIiDKdYEvjHy0RoPZy8h9sIHr4AfJ9Hr6zEWbz835/vwmYI3BFuTYQosgjT8qEkG8Y/ZmkhqNgE5zvXctJ9xentObzoAkycwYAe3hZRpaH9e3zcA4VNbTCKH4Hz3ZGI03YOnP4ET3PpjbRPUyU05JcMC8kD347cT4nIijJU72zN0pAUlnT81QzWcGCROXWabFg3PsGjMoZfQIekgRep2F35hYAD3/uR6LMh0mmXCfJIWRS21STFWOTd1DKVs7FFMUvVR83czRnGFSduDXQPMaYwGyuuAyNnmo8rAeQeg77axKOypf880EWq7szAXQ0g9nuFpJWAB91vEQupuWidepoKPGIdPVTthiH88TiMAAyD6nuHwwtvtZrTZtezLIs/OfmXMHu5tPUA9gOW5D59BW2Vqn6Jvdab4bhF2WOYHURwWlp51oD5wvsuL5Ss5/+TS+Zfw8M298c1uheXu3o6dt6F8ponPGEnxvyXMoJb9R5g76AeMM+1k6d9debuUc+IdGHhbMm1T73A2UD9+Ps8SfvlTZW456yQVzhwfxcvTEKEtfVSYrB0IudrJo+UMYNWC8EGaXp+OObJk/QPkd8vuGNITwoyFbB1FJw6QAMUm25aXd6onBXGEI8/Y9mKVN81MwamqGTwYTXGbdmytkGkiIh8teJg9YjXnWpOmZrRSayUIlUx6HG85Ph44T+Mky0T8Qfw17l+sBy03hbpptDRHldsx9Z+xzhqp6O9uAAap0QiMhftu+KdPV02t7qaCgGSCk37dmlkiJf4HA9uVknOHzehyLccDLcFjRUNZIE5iZHgcDrymNCiE47YHqd95B8nDZRh+h1/Wnw1HVAX1MH98XKBj9uRFjsrY8QhKbQE775dH0wao3jci8tK34qkKDlXhOiZS5IlyOEumTJwUn
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argocd
    type: kubernetes.io/dockerconfigjson

