apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgARNm1ojpNxd1q/fHgIUI2y8kRO5DU4wboaX+oy8aUxrkA2TAyMyqg6sA2n6WuL30Yi6xl/f1CpJFrU7LhhvJ4Y0zy5XFU9+4e4WfN2eAORvgnpiOCCuoRYXGGPndv3DjHBy5a+sN0ADRO5yY/yKMjFkbbIcR6MHTOzRDLbriazfnNrxBkPzk9yTAZGmt0n4DCZTXYIxLsiaKL7vsI2XDxNNxyAKpzSZDecSybncYfmWahjj77WB7WvI810GX9iWsMkuQlPS5j5RS0EqzpXfWEKZopOVmx+Gf0dxNLmEYbsi301eU8c++KQvQtBbTU6W5S2ZagIuHEpEsXTnGLs6mjRswV0so8yHoVhu/QPI18D362VAvr/wgFmmh5EniWqQ+w/vBNKB85kwwnqBdLPWIn2Ig30zn122aXXFLuEWADliumjfX4ljPG8ips1+ccuOQcRESx/qQaK1tJ+CQR63BKeDDO3SYSjWmLUnPBvoYjQf4tAeikvr+eKhu5t3D2iwTkC/q2RX2ORrD4bcPMn+E652Zv48cXcvjSF8RQk4p7zwW5sIXtgjA/TgF9T98srzL5nyWV+2TVtfeLWr/N2153NfQT6LB1Vrx+AU1kBAgd4Tt7W8t4OcSI9mu7e8KOqURhcd8APC06Z4+dkYND6txmxcqapmSK01fT6quuX4nPkkxcMptIb4tKh15spB4NMoBkGMyc8IdAl2ZjPb0FlQ/T++vV/BDLdOeOvNu8Zt2bcGiLtwLMBLyGOFpg62/7VReH4hbsEkdl+BMUMQNpq66aS+ZaQlCEh0VTrJaPgcmCf2/te/QAGtAX67mnhW3Os35BiCcH8F6Rl+bEobCba0viFjedP6gMhQEw/xlnChcU0yoOYqq5YZtvF0XSSQdDaJelkJylK+ljmVnDHK8/hRzagdOnIZ4LAnNgRGC891YDX80YgVUjlhWirq5j0byB0RnCVj27OVW153yp34ChVm4KW5yCRkVsz
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argocd
    type: kubernetes.io/dockerconfigjson

