apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- prometheus.yaml
commonLabels:
  env: dev
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: prometheus-community-kube-state-metrics
  path: patch/kube-state-metrics/sc-patch.yaml
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: prometheus-community-node-exporter
  path: patch/node-exporter/sc-patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: prometheus-community-alertmanager
  path: patch/alertmanager/sc-patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: prometheus-community-pushgateway
  path: patch/pushgateway/sc-patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: prometheus-community-server
  path: patch/server/sc-patch.yaml      