apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: argocd
  namespace: monitoring
spec:
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector: {}
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: alertmanager-main
        port: web
  probeSelector: {}
  podMonitorSelector: {}
  replicas: 2
  ruleSelector: {}
