apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhsso
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: rhsso/operator-install
    repoURL: https://github.com/melak-cmd/argo-combined-demo.git
    targetRevision: HEAD
  destination:
    namespace: sso-dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
