apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhsso
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: rhsso
    repoURL: https://github.com/melak-cmd/argo-combined-demo.git
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    namespace: rhsso
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
