apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: sealed-secrets/helm/sealed-secrets
    repoURL: https://github.com/bitnami-labs/sealed-secrets.git
    chart: sealed-secrets/sealed-secrets
    targetRevision: v0.13.0
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

