apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: hashicorp-vault
    repoURL: https://github.com/melak-cmd/argo-combined-demo
    targetRevision: HEAD
  destination:
    namespace: hashicorp-vault
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true