apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- github.com/argoproj/argo-cd/manifests/crds?ref=stable
- github.com/argoproj/argo-cd/manifests/ha/base?ref=stable
- github.com/argoproj/argo-cd/manifests/cluster-rbac?ref=stable
namespace: argocd
