apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hashicorp-vault

commonLabels:
  env: dev

resources:
- vault.yaml

# patchesJson6902:
# - path: route-patch.yaml
#   target:
#     group: route.openshift.io
#     kind: Route
#     name: vault
#     version: v1
