apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCqpyZDLPMr4WxHAxmTPGpNbmouuKvdwNtJQTFW6K+VSfk4Gj2CrlekF3QguKl/tquwNd8m14icIn43Aw82XxwHzMvP1oUC9b+C+7Buo0JRy/iUGJz6muVb+rjGkZf5pSwMMtytOXDSsGhx5pSBxMUZTqiMaJ/i3sCHffbaSy8Pq12LvqC+n2+ynqvNL1Ee59rT1RT9/Z1lxrR3IWzvJtdsYY0TyXqcwoaaO9Xt3ifo11auONIhJIcdP3X3FE8L2Pdfbo+734jtei5fddQjjW9HcJ9sSvbRelxb5W0Hiv8CBHLVSjrry+o1mqgRdhhCFnM/eI5r0af39mUlbNwnbnXLJ5QwCPI0OnNAxQmqApc/gudy2o1l7WIoU3iccilzq9L826jTOAH1TCNC/PpgzdUhwP1iB2PQI0SjN3XmEZBkjAG+ZL5h+jhXuiGRkXde4AfI0wQPAAMs/n3O4ZMVkN/Z2bNun5Z4YQJV98fvumvOdN6GPeKK2LeEdvFQye28/zhH/I/hKLKFjoA93WmtsmH9Y5NCmbCGdX+IZ2XIwo+9RhZ/kUXJpBvYQz3V19IYFTNs2UhBVikQvTgpi1WAn8rM7QlQnSVWcwdUSdrthIkAa4Pp78MvArzciFswXSrWyfVKWI3jrftaFTGAdM+Hf9mX37DfAJy6VVdCsxCGhgQ4L+/zBdWV7QH3CU6RgnTjc2eqyG1lrwzL/D04H/uTTrNAXO32F8K/RsuSvW5+EE4yCflq3vRrqLH1
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

