apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAbwEL1R3pL2zEC2i04mScaMe8KEznjK1rkW2sTNB9rS4a/i+uSQoACA7T9Hqc1w9KsL8VubsU2XEmEth1MXHk+ZJ41gYkT0qArbpfp7NM32miBbRj5CW8uOdFdNQSPwhKd9V4YIDLhCykyaj/K7QcCCx3yaBt7GkJ89gLnjCcVKxNffF6DLs/d1wCtkeKQqce5qeVWjalrgt22Z8MKZjwIcBj64d2yKkBm1Rb5o1KkgXrHVeG4/jI4n9uXkAb9ksfog49yCfdnBF4jDNIsBxDVVu4XQo8m27j+hsVINkPSznJ5tLD2b7gTPumUsWbmDy2cWx5GCL/1oy8sKheQV+QceHUsmEzIClMoUeyPK/6j1RIgcifq3RPugtaGT3R4QIkjT7pc/45kYHcRWaTEM6UA216r3PGj7CY7yKg6Ugp8MpVpIqWoNCD4bYFc/spfa23DFH3RbXv50MPRnntr5vvpGgGA99kyls7yk1NhEGmS1Z498EELo/JIp25UNVVwg1qpcxXLMoqWrgmxHgvCGRpHXex/7HkleM8/9+AOLE5JYd65d3eaQaJgXUgfeAquWOYrAjmDx+nfY6Ou9F6cFhBBCaOogXinO5ZWMW661TWJzJMD7DCU4nezFCJNLcDrCWVc39mEx+QV3wCfvwZXqUlRD6owmc0rCYTd1DYFi+glRP5DImcZFfDbcOgjvtb/akBrwioAI7trANGvG1lglhHYHp0z0+MzLhQNYtVQ6JWxfvIA5F9r6/Iz
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

