apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBN5K7H3JEKcZ4ciytNfjCGv4SrxHXWNx4z3JdA9UqNEnnksPai/mzebPgVxwmGXl1ZA3BVgMkwKcefkEyH4PPlWcqatF20sOSMCaAagiahVN0rfakwWp/SDK4hp/h0FpVJPwDjrBpjXpuLxLmWOO74iK9MZ7djJ7jJQzOnS1f1LGIbDapDtnP0KrDw8ChRH/ChFIEyJNXsUFjBDCAoJPxFXfOzIXmEQifSkt5OKjCyAS+ehVLT7g/+e0IZwHJAG6Zj5wTZdLDEi+oPVYTiNZO1Xx0o0S/O/cbBFmVRQYzxVxuVwI7ux1+a5Gasb9wu7649oc8fj479l+zoazLJKa2r9eD3nVy59HX9huXoZXC6B4Sr4oVyowK2XGgA6YBlxN8EL9W0VEOYUw0+vov5xQuhGaIGnopb1uZmbhejrEDGqHAVDh/d2S4D3pQko2iqnVsWce6VRPGNUf/7bgFI5XdK0ECySe7lVt67n1ny4DbhSx1CWmPePveyh1ZfdxkXBSqR3BO70RWi+YpnMjYYZ4UVrCwFS6+aME95Oep+hhy5IFEzhZADXuH9jNxZ3JFmdG+TDa3QlYT79c3ghfiGh6s/MGLKPOMkUYJgEsfyIdKUWNloiZA/mUU0lJ8drc8bIcR+CrJuE7+vbC/dbw20BCeU3T102+lGdgO1mivu+/JzI+2bOqkIJSPOzP09qkzlJOqyq0sjPt58T3I5410oX7MZGPfCHG2MwvNBznefbhP2CyfezJwkLiLi
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

