apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgB3QnHOK3Csqg2uNoJxJOOpDO3XQP3ZDeXN4N9IAvw/p4Qqfn6zKmsZ5IJDtkDGrZdutYVH3EcoROgBVjHMu61UZOQmpUfaHBSYRQs8U8WDh6W9FPBYH2Up3UsjblVDWR+PIs1PkMKpbslzYLVSl2B1oYqaILtelRyQ0grmA1rmaMKYZa4yvABfkoLYb/jZNPgCt3SeqG2ifi040P/L7FyTpopU9fbuVa5z61gyfgXylvQrfzyJyvKBGqWISiqrab4PX/UZEq5ixUUi+V9KxbK7RUo+pprzH68jK6hwDkthV8K1Rr6Ufp5fgKGPgrYCWinmDicMuTPNwAf3lrgYCr3uVn9GCUA4L3OPGCFaPO9gbSIDdM2Aqh3FoQAZPz64yuXcIjuiKmh7q7ZmW7ovc5/994m1AQgrvEgUuGIGzk2M1/iVxD5jW8HBa1HoPpXb4D/Wt2JxBY5+YqS46La/FuBzXF3dtu1T1TrUCUc4ANmJ4gE3EDOfzs1qeI042wvKjHZtPNKi8rHOnLaOf+MIvBdpExXDMyrQ7gRmjoe8vQTprUWQTzk0Ck+umsL6Kebxs/yUfJcUEz0+F2zHdtRgJGM/GWk62+suLzKFK/FZxddk+eEEMMtsPa1vTUXMVlObqy9Xj472DtdULwLlTzEsPfmL4JT1mrICvg2eCc4IEFiXsAsA32aKnwyTvAHgFtognYp2gq/16NzQpQ961x36oOOzKQAW2ojcSXExEuyAk2lUL4JWfcb0p6pF
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

