apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBMqyHdOlxviIZInAD3YoZjlodi4GJRpo5p4w6bevi2AIexlgc0soGH26qS3qMIUfSpFoo7Le2mEGg3WzBOiTwOQXuCFicioOkxCFlwv44vc6ikZ6tApHsFQwgt8xFciyg52bJ7tx9eIeAFMix0aJRzHm+MYyR/u+5fl5l7arN4CX4kGwwJ8Zx9NwyaZ53TpOstEvPbf8AagdnOZeuVNj3TcURuLtkOvkmhg1cef2as/arNojV0cmGpehc1WDWuihal51MIJ5l4AwAHYPoG08d/us4FCvk07p8XYnFgUGSG1AIB4IN5uBKyU5lyiPnMZO/SQvD2T9CsnM3HXeedTcj58qYjecgThp5DgYRq8g4x5hswONNI3sV9khRREn/9m4qLlaj/bPecDM7yiGHc9QNibntWAMPocknGs4VEjsr7ig/brKkkTe1PkwsgADKAQn78SIEHaL/7Kd7hQgP0o5BCFDYLQBslFxyRt7mMPdvuUGJKWYjFAoELIcda+ow25Z61e+JDgttY/i2+T4FoMLROdNT3LgsYP6HIG+5GNFOQjYMpzRqyBSYL0YP0f+iSTOiBE5J4vc0loGp1+1WHfYxlv3t46Mq9AVxbRLSt9lp24yJAxKcqEGJ1vAYqHtigXkKy+BrdgE1WCQgY08g2KKCdqq1YUQq954f1/KBh9oItffyjEb9sO6OZVotJqDiJ7KQojwIOT7liDXdt4ieoRqG9yxQF1dC+K4sigmZuF2CL2ONXU3xXcPQJ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

