apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgB2SFT5Mci+GHbPHuXFUM1RtbyUc0VC2fpXbYmRe8G3Q/46T492cXifeyMb8HeP1RCMKy00o+CIMtJe78vK6Owt7YJCjWeDiD0LTBIUYeShRzkS2n3kqzkayvHo35VrG44zaI70M98NT+PS8D4cnSXT0EmdHBoaNhgIa2Vc7FBMiElYAz2z3EEfONhVen8B33gN/QrqZXNXBQk3DDtSVRXSsUOkKECMrKkBZL3LpwKIg004XiIhvFmcXktEvckAu1lQxaqk1EFcwi7jwkUa3/TfkoPdo9MQxCMJRQftPFuK+t+gU7+vpQ29qDXJwiJOqxTkvvMyeG4jaUtLHr2Sq7SO1E331/l+U5g6FyRQrdyUUokivBR9fu23yfSQbdYAvMXFvENjm+QdrfquF4M7jv+jH2NGfmuYkUIJ0ltfLAoMQCyb0TwDfed1VEn/Ii5Z29IdXqIn/69rrtr4vdTlD0pi41rvb41nDRGLHMjLCHXF4wERlb99fcZKHgWedsW/4EYRIwNIBTKXQnr7d4Pk1O/3SnRuewPossblgHqit0nfgeGaF424sbRFtMbxghP0bQ7YJ/b8lKNwqwgKQ1l9pTpKGvif11ZMkYdfNk43KMoP80mHA/SX2eaJahxodge3nt346xwiaCRh9lo0lmZfnAcUaofWFr2trMbYYqnLfR+r7Cntrcb4ijFoXGKi0FcAZF+voqQ+wNQKARpTGGL7j8aCQBnufLO8kpu+qwIE4JEAIa5g2XCgthek
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

