apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBNvczd9NpVSvPzmEEkX2+y4byyYILnnHbzRDn50xbEg1xRUI/i06Z6B0O9eN2VvuNvusvrrF6CoaIrBujAhjTK+oo2GR0JEduj+V/kYFkxCdG5vJcc2Azpwl2bpyi8d2ad0u4yog8g+OOJPuuiFfljVDqfN4UCMYC5uFd/xFFk25xVON4Par+oIkdVPjFyHdY4tNWuLYe7MRv28xAqWDuRU3fc1foXU42AyjgeImWaykcB9rNEividB/sch621N+4L2mNc7iiYUT0yQOWxk3B/l0Lt3GQZ6GiUgmXObN8749MT9GlocqI38zVMZJHVOpsgXBMNT1oZMlLO8IkQ5YIEm75L6BUkgk9tQETurykj/LoiFHTCG4UomSfHbEQTcuTZNilyUMenVGpDHJcAF0AZl1K3gF0Mma53TsNnGurwa6vkZ4OdgMKavlORRDYahtLbV9LH51GKHQjMl1I1+CtAxecCgInd6Y30g2JxYL/Jflmbow7COi3sJzKt8kxDgSDGk4KsrjQda4K3q2KQ5bWDv1qmP3l/gQ/ipQUp4yPCFw8lRbk/KAOM6VPBLTqypQAWp0ELG3deuX/qh9EPL80Y/HaSqnIi6HC5Xo4+KhiSRQoWTEVE7ROxiDEfbk1pOHD2Et7GuHOzhSn8s/vFIt3a51kT2WzyNZD20QiC8Z6TFTnm7O9oEoHzjWqvFjmsJHjrvADUfUBZsFGl4/IGpGrwTE3OBFHtnB+nDN1jAJcdD7eDQ1T0eexI
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

