apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAl4Us7SPydKhgfgur0ppr2yyWEfG/bU/lPaeHw5DwbPxnXdl4SoYozAqWPyqtUANJBMn1uX46jbsP/7JQPjfUgztuVJtNsSH8LAYLuqHKIIwj25I8OHEVrS0gkJaKsDdgsqeSJ6RzV6AEeETcwUvFC6NOG7/jFxn9ElvXTQ3EiVxvPd22NrosRHJ3iYUSgRftGFqYMXoki9VVK0ebypyqu+kZgNolG0TkcOMlXZ94ldEOgbKcfaxO0Xd7ci6el3QNOf/oS9nLJWbJIkg+QRB7wcz2ZMr5+eozD26o49Fi1R5yClFsZcyXfA8aSLQH5z2u/gmYpJWZviNL6KNQ+PkE31jzCI9sHzFDxMmWdEhV1cOdhssYC5Jt8WmOhMaolaeMJQgXN0pY4JCGFOS9aTIjHkrHAGyjjuwG6OGY5xZqSkgcDokViZwqVz1q4kzC/N6nlFjhttVX6m9xZDAbRLPwnwIGJ0Qgqe1F0KrFQqYIkdVaGA4ZAFFVO5OsoF/wNyGCWpaLtMYfSHxqJp/oPV+YmSeatd+6+veoqhnQqk3zPNVIJSfvfaOecv0GmBAS43/A2fKiHxrBQ9CXEh8x7ELTFfCmWzzoNa7BkGR4lERnCiILTDURhu17FhwmniWDgwGPQtU5/QgXWVcCMfV5weIpfKWDNGmJ95H6/+HwTpX/OZ7bNxI3h4vRWMTbM1yd68JcycccO8gmEpK+gmaA9fKu5lCgREz88ew2LV65ZnRQ4uSPs9omIWj8L
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

