apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-events

resources:
- ../../base
- event-sources.yaml
- sensors.yaml
- githubcred.yaml

patchesJson6902:
- path: patch/sc-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: eventbus-controller
    version: v1