apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argo-events
spec:
  encryptedData:
    .dockerconfigjson: AgC1E8Z5tQlNt0SaN9J0qCTsjqepD/B2LPUS72m+U8e06Wy71xfZZYdESHPchs2jB8rJDZEjjJ4trH2s1PtyKCJWgxu4e0gLUb0V1TAE7NoTBrCThV75SmDZ+cTYm7/bDdem1LLbMVUw0ati+C0qu83amEJ3KwhA1VfLeKnTiY6u2vV01BHcQ+Qe4B1OUbhW4mKHLJq28C5V74qU/m6qN63ffwxSifx1zT3J/Ch81durfG2BddzDBkSBPCTYWiXMdfyhsIvcs0BxHZWjjaC76rvHCRI/R4LL8VmAfIOU79i3+kgVLGDl77K1+1LeervqHbt8nbwB53J6XdxK//WD0vZvdQLogZ/lcEjKvWmiubq+txMIJYgm5ZYOq/Qt00u2yohouTB+o8JOL89BtzB7M/B7n1v8jYBZwJFex6PHUlC3ndL8nV4NokPXZ2CPXhOPScvNuctky+2wdY047Y0Coqf3G5gHj8CiTnky+DYvx3GJR7MxgzmJQkHrWh9qDKOk88nEIjdsBVPMdDLwh1UqTG842vMZ706J/U4Yg+kToIjbRln0dkqIFatWyJuau/KqzV5pEHXR88sFfAoEWv+U+ud3LWrTr9JW+7WWYaPjlfph5tGgNvDZlUpetx18VWnGGVodjwocJmatDBPHvDeeQzp54XXZNlDMHFEzJNII6D2p6k3VeRnk+gAsaNprQGZ2vVGU971W4284QOJFsa35MiRudLpmkfzSH9OCqho4on/joNrGRfTPFmCZpIn7WTOMydXgfSWnEy6sasCsJrks6W8XFzGUXpVt4UnypcgkfRGg+YLiAh5d3Tbi+csdqsSGogEFrFFySJnpgQ7jh9daca0jNUD+t6stZ7E51FBFJm60tkXqDFqh7yi8/PgmWp6MHbObBitZklnYjkkSalFUgku5q0BM9efkOP8eQVvZWk8+JJbtHOHBM9DXsNshHm0vKvXz6qmM5hTSWmphFB5pl4DQFuXjyQOg
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argo-events
    type: kubernetes.io/dockerconfigjson

