apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argo-events
spec:
  encryptedData:
    .dockerconfigjson: AgAnQzVPPhD1OaCEiezE5Ftd4xiQ2+X0MBvYW9hVCllsIwyzepcKdblJItW8RbKuoTpTsl7V1eVQRWVoqc1drqSo7gfARkQQVQ52Lzc9YfLZz3HqraOIaldDIi7bMkcFv0JYuttRrna0x6WaL9qW6S6EqITk3gH72I3v0H6xxBnUnUUbPbosuJeoAPwbkFECdrdJlPM0AtkhqYO7CjWiWEv8jcmnJzjzy16WQ8vmhSSrbAKwaiPltfHmFEb/6keY/Jpmndl7AHrt8XYvaG3r6e9l6YOJkaMrwsEhTLZcDlAYjkHQm0CNlh3+6UgQsfQX/OhVReGOZ7lS1ii9KnJJtcO3fze/myl+ClSfI3K3okgNcppOOse5i5SOvtxRIeilc3NqHisYiUpefFaMoIMvadePjnPM5Cmn6dT5iB4oV2yN8McOdHGcoLQ7ouOjlMyLTLrSeA7mubcMh4vblI7XV/zMMgxkkuAcj5RAajyCsdP9sgjiBqr0c8vbqHZs6f6UrMLPih2dTwc8dqZnRZDs9+LH3BuH8bkQn17C5kerHlWHV50c5p9Ymj3No4iN5svYZD57526bTe2MSkCK3mALNAoBSgM1SpCiYYQE2ogy4nL5HHWE/0A3fHb+Dm/aT2Hv/Vk3MeBTh/ZFNQKAwjDdtZ37OChBfI+DcIYTcdPKxeBNW7rQLXj78DMbhjap5fE9Zz7p+uOhwarFNOyswMqahlqlDQeIZUVtAChP4OXNibUMU6bX4tOQmIlOK9+k57awrbrmNOoRBEFpCRcuf4dWR/xV1zJPV5Bz1juPTj4LQPcPyib+L/FhMb8bWHRaebh9FUt1yhLlQ07fjF2RHEYpdXE7b0JS2GpJEth4/kVqq9kx2OCPq02gsdzuz5VW8XA2pbHpyDcVqh/0itfbxTU3QuBvo2TClrDjzAHMw7miVKaVnDTcAYcwBO0iG2GKzDvZHRx4+i3ZBsqKM/nFcntBIT3U20YYXd9+
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argo-events
    type: kubernetes.io/dockerconfigjson

