apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argo-events
spec:
  encryptedData:
    .dockerconfigjson: AgByC94GG6FdkgJbJN1PwIY5i0xLOGUOIf06lRumY9YnVC833k1Sr0bXKh2Fgyw1N2wwTwRKNnfQGIJscTGqn5o96C3b7CuqRyQdwzmHvA5xk+6kMXNDbN0sw767oUd9BLoeIsQnHRSRU2lk+CqXnoqnw5IBmina7v4nPps9D3eqnilCf6cKEiI3ooi5HKKaYYwA0TMxjPebCvQPHIWsu9rlPyNpXsUv8MXVOuZZ26s/3ywgtijjElbZYOCL7xtTSoEpxFPS5Nb8nv21LpmJOgTZNIHFv8F1iyk/TWVGM6Mw3s/S52B8yFtjYeRK0srzpYMhzPKKOAgWbB2FYx3eQ/WxkxF3ZIePkN3RD2Y/ejRhZLvwmGMg06ynnZ4u74WeB7Gmo8y2y9RwkIaBUA4KLoyF5GHMqd5exU/+juqp+y7cRu9I1I5baD4eKvCoe2SnPNPWuJUaxBTG+374mPK35vWRQ1v1hqagsllIoPAR4ZheystPht9En4Sro9tREREJ7nsHo4JlG5udQk5rsOYeyF/s6KOJUYjNh0zJ11FYaEw164yitZQr3ttwU+RBx+kErs25tOIYPuF0G6WamEoa4b+vf3mZLoeYHtrvVdd7S6wwFwZRO8pjcRw/oAW5498O8oViM9Vr7tm0/FX9yXF67gPNQzAfsVWunSsJJ3BmOszJ7m7wTVSFxSHe1Z9+Y1jFDeMVffc4FDBhSBGFi1YtKzDAfA2qUH0DCA9AHeWCDKqUtUMtJvPmqZ2a9s/PWJ/oaUzdi/zUl82edFa1g7bCIIQUsVr51tDStFmtWIaXs5fNMVrp8ENj9ZuMr6J+a+CWff9z198mvjxXr7Gtnm3mKnF7hO8rOGYat92skIOkhfQQbDn7FN0oG2ffd9FXu0uoLajT4CsHKa6PErsNCJU5Pvj3vYynuYGDtzbvEhz/c11GTGoS1CnevUsFYvKA5t95JTFnrxTHtvBuulUeCa3Gv64I4NzIWLs/
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argo-events
    type: kubernetes.io/dockerconfigjson

