apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argo-events
spec:
  encryptedData:
    .dockerconfigjson: AgBfSNkOTWYi1wnknYRDn24RFyWKeEdKZR2t0YD8iZ8IkYxHlsFFoOhHbc7wXolZUNEC5pVgOh6w/avEpu4tkS6WJc93S0BGpbPRlKo1vcbf5PULJ2NeOI2EgdzLZaIM0Bqa24cxQup9R0lg2Io+cqSOUUor603DExwY/N06bsZ1+jz25ggCP+e+BymeDRDjQ2fr86osh4eJ7Fsc0HgkZM/jvHJy2tPekQ7PgF9IA4ZwH8d7Zbzf2WdyuChOUXNNm4NUFBHtTdMsvDGUCItso+8kQyj/DMKTWyEIR4RUfQGQRmE0foDYxA6IisujCr1EIhfpa94IZQ8bG2zang7S4I3fOPK77EewXnxay3mJj0yrAcmcvLbNzr9LJfiq0cx3KNJRFLOVbduuwM7oHH5B1awx7wvdWcR0ydHT2Th0POY+OTiR5qTZBHCd1ZZs64bCv+WND0b1+VTZZ+Tx4TQo7iFk9nigu8PXSXzSm6Mfa+SSzhbqDqzWfGO7o9kjpGgULji3Yw54VslPawjO087BW15ItpUBuRsJT+kTGLuAYTNpUgpPsmcDws589mZsvmBe9/L7SV+ZY1/2W4VvU/o8mtsvla7Y8abxTtu8RZem8LHPbMJwyX43RM19f5TNRanUlRoJokmwj8Tl4PHrEUXzVUnsgre6yPqM8vQpJ5sUQeN+BReRjzsZKc7kJhUqh2aSgh4z9MMp0FlEFgqfO8juW9yfjiUPhrvHTjIM+2cUUR/nUcPoN5VSKoYeVfBRiv1BQvLXvntSIc8niaOlqpHJclKcSfupQERgMt+7k/+BzywHUdajNbYjCEmvUtnA6KGAVTum61iWKDniW3qFlo7ZCdCWdkfAEaXEQLaUIlXnO+Cvqvd9tY5nO21i6fzp8L7/yvAf7gi2mx7K1DWyBNuHMQHlMjgXZL22vjGx+xK7Rtr5gzFlhuErEzDlivqDtBRmUTgg2+uYp+5Meao6HNgqRkRXDO0XjVEC
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argo-events
    type: kubernetes.io/dockerconfigjson

