apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgA4qv5JFfbbeLiQ5/ufmXH/iF/xbEbnJPTRkqUv5X/zkM3wPP22/9XWxBx7HjPwiFyA5A5MzV/bcdHswfz71H+kECHXRw3zdNbu+RnNNfM6BImzeJfzAgQkOaJKAPgjNQjHtkhB16PqyiDn8Awsz3fUwj09O+nqU1ut7MSDJfA9Oaimr/fFdeJw7sa84zeVJf4cRyMAF2dkdbYBxx16ZlYKzTS3Y1Svb1w3im2zqDtVtHiSEmD8Gw7EY6Ek+ezsmUhMPdCZEkDDlTv9ShPPdVSiEfh5HpJ+CpRnIHpr8OKuEiU1cRDMLNO+up4XO25rQxlaZR2UoS8fSX7LzoB9L5ECgERxj0gW27vmOZIBN4rh9wyxHKtX/+OAucow//tFTk6BA4K0hGuu2q3cGbEyIxemSG6U7ViF2IS2HRv/iK8CEk/BEz/+rRuqP5VPJ84ORsmnupwRKDR51yLGWqwWxJc//sQ7XXyVQtYgwLme2ZqgqiAEj9OHqGLLJxMAL8g6xjQdOIw0GSDLrAGzacUDFhQaUm6klatpjcdECmg4kAgvM+TcLnWsvK2MI5FbQg3Zze0p0dQqNwJa0WiQ+PUg9Wb4iCXRSgDc4b/Kjx8rY5eZ8NO4sl9rwwGEYds9hQcvyd9Wy7JZ+AkC/OxX4/K3Qunt/4CDrlbq46gZzboS8/mhh7bTeS/ko+3mTD0N4m3sN7md0H8VVsW8NK7EdXcj8vuVbFsom1y3AXnLxUt9iXz+mVIbIVmKpvKTjyC43vuyLMxv23oIi9EzzOcJtA47LpRBBQLn3kgXsRbr/y+0eKTJEl8JMjWa5JM/EC7ZVK+LOHz3wF+x5UnqV8c28tKl3OEhuaZwN9a7Kf/IfnX4zcqjLWiKEH6EPRdnWdqsZi1idnTvbq4RTPGmjNWKnvLRSB1ug5DaQRd6qGRceRzkTx1DxBKVdII/R7lOmBRHhhy7BDVHd/Z5JawPnkFWyTrXkdoABofkix9A
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

