apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAVNDtW2au7NY7JEV0yRpBq5Z0p0eJxmTobLyT+a4pKe/XOSQ4v0LvpnD3nxBSPks0g15z9PLnBHHHBZC3zuoErtykSMICir750+RIqiFdK3e7yhMt/tTv91rPsKgV0Pk4jm4YF77he6UdDhbnVyVaO9Zt0vD4rRiIxSUEq06ErdxrDnwMDQVGmOWKCBpboazqZOD/aGqv+atfImocYJYRxt3pXzm20D99zM0gC2gfLe26y8R5cGrZXU+h3U0AX8CZRriS9j3KwyUF1CTR+NkU9jF6Kv5W0Bo3DkjoBR3p/b2LoDV2iHL9cLXFljcOkJkOQ0ayRdGik9FDdzOHXAPRtCorOrD1Klr7tLDDivKR2MMS2UoZJQ0nfxT6DURi0RioMfI0gupnyJMcu7nzt7SjFzz1C0+xkpDllRY4O9ETHr4y2UtZzIdFcZuGGawYzEFW71CmUg8gcn+4FiUZlUiCPFwy/U1ksqgJAVJ7gsXYudJ6sQUpzMBgUeyKqA7DCEFSDnbOGbX2VGFKv5mpyVLN4hPgXEfj3GwacLUUqTbgMS5z64PdcrR1bBu3tjL0UycPFkFP4o5v29lvBfuby4MeQx4DnP2Ae1zNTovPaFNf5eGw/azjpIkNqKutc9sxz4PhVKiWAL0x7DrqAaO5Zjoydd6aoDn5dbsAlaglrg4xvf18uJYqgtaTCPItzaJ+qTYqLSY77GNB609uBlX5KNCsvA00qMCXXJT9N03Y7LjAMKEAYT+/y92VPCJP+x1d4v//M8ckAj+XwUZPOkJKuzxRAzR8Yu8WR4JX6G9wvzoREMBu3pcr372qlHNP5ZjwIRhDRxMEbWyz2nvpm5T1YKZ3L6/eFk3lCIBbUdWvEFSbuEpijEfMUeryiNO3JbzgcCtWA55nxIBmdBJcG2LMDL1RUKMzKrCT/Qu6Tu9b9JyO147vnfJPYBQ/lqh7j2fr7A49al9nyOoQGultKBnTXM0X9uHcczgRM
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

