apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAJiIwttCkHbPNDgO2UnEEdKonAZLSaldAVy2q9DVNSbF/rY2a8iCKMZsfiMWDtVCN3RIUD6Ew1bqfax0ITsXt1VyVZSOwh+y6HvDPfMm+z1X8HBp/TpA7rk7pJot3594ezrkgWrRVUDkibVxKep36e3c7S+sEsUJp6j8fTPRllmk1Xvztfsx6dYyRHVVE9VHP7YRhdwn+qUMU+sJsVPVcLZl8WORjOHbBaETGCH78ROxWqDUqiXnh91C5G/bHcP8lsq97PRlKwpy5gbZJnM+lGKtV+PPHu4VmcvSbDjmAfnFavYT3d8gY+MEgN9UuBQJAwEwQLQHu9Yosu3NETmm0EPVgZ6+KOEtFdOSz1R9Jo5Wxm5odz50zN3/cuOe5P9kiKWQdEvFxjnn6u28GYC0U4V6KVCibm8ic0uLG980CKWEYjQZajwxUXWDo9M2QtVImI46fH+azgsZLb3A7OKb8NyoJC2yeAlEcXFQ28T1/fO0wolO4eNKtyFB+Ad0xfFrcm8UCO+czoP8XSd7JLPDSxyUc1eDZLyzX4j0hhdyHEjUTSHm2rRAhQXjWwbGOTcL7DFeBMM8QaV+Tr5mjFDQnhhdCT2l9c2hTRf3H57OiLflUlZozBxPh8Z7ZL7vMgzhyub2YWpMwm5OsgdPh8n0nQv/w74AiYiuQt8HEV4zYaQTSKpMfsrxgAgQsffnVNusHogNtZkI2K97+R4D4zDGLBPs1yo7HmEThcbHj6N7Yz+1pYB8Sa6JyqW0PZvoWXuixJiffBuTtRuncF3Dh2ljvtPCgfPwrGwiwLpHvHPqJr4p6GF7fPxQHP4F1ruyMc3SoBANSi1Hgidxyh9x4n8oWmkeKF3osZBDmDWJ08Ruk6rMt8PfM2GD5M4C8MEbI45KlCgnc4RPBf2Q2SSeW8Xhw8S80gLxKk9/MVNpE4nV1FD4PYN35AgFcXvkaIl4tKutryWi1QwLF/BorMcOfHOpadUQiw8jW7
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

